/* Generated by            cobc 1.1.0 */
/* Generated from          beginner_kadai08.cbl */
/* Generated at             7 18 2015 00:03:28 JST */
/* GNU Cobol build date    May 19 2015 09:51:19 */
/* GNU Cobol package date  Jan 20 2014 07:40:53 UTC */
/* Compile command         cobc -x -free -g -debug -Wall beginner_kadai08.cbl */

/* File TOUR-MASTER-FILE */
static cob_file		*h_TOUR_MASTER_FILE = NULL;
static unsigned char	h_TOUR_MASTER_FILE_status[4];
/* File TOUR-CONTRACT-LIST */
static cob_file		*h_TOUR_CONTRACT_LIST = NULL;
static unsigned char	h_TOUR_CONTRACT_LIST_status[4];

/* Define perform frame stack */

struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];

