/* Generated by            cobc 1.1.0 */
/* Generated from          beginner_kadai08.cbl */
/* Generated at             7 18 2015 00:03:28 JST */
/* GNU Cobol build date    May 19 2015 09:51:19 */
/* GNU Cobol package date  Jan 20 2014 07:40:53 UTC */
/* Compile command         cobc -x -free -g -debug -Wall beginner_kadai08.cbl */

/* Frame stack declaration */
struct cob_frame {
	int	perform_through;
	void	*return_address;
};

/* Union for CALL statement */
union cob_call_union {
	void *(*funcptr)();
	int  (*funcint)();
	void *func_void;
};
union cob_call_union	cob_unifunc;


/* Data storage */

/* PROGRAM-ID : REIDAI08 */
static unsigned char b_1[4] __attribute__((aligned));	/* RETURN-CODE */
static unsigned char b_6[50] __attribute__((aligned));	/* TOUR-MASTER-FILE_record */
static unsigned char b_8[132] __attribute__((aligned));	/* TOUR-CONTRACT-LIST_record */
static unsigned char b_9[1] __attribute__((aligned));	/* FLAG-FILE-END */
static unsigned char b_10[1] __attribute__((aligned));	/* FLAG-ON */
static unsigned char b_11[1] __attribute__((aligned));	/* FLAG-OFF */
static unsigned char b_12[3] __attribute__((aligned));	/* COUNTER */
static unsigned char b_13[12] __attribute__((aligned));	/* TEMP-EXPENSES-TOTAL */
static unsigned char b_14[37] __attribute__((aligned));	/* INPUT-FORMAT */
static unsigned char b_20[47] __attribute__((aligned));	/* PRINT-HEADER */
static unsigned char b_27[43] __attribute__((aligned));	/* PRINT-ARTICLE */

/* End of data storage */


/* Attributes */

static const cob_field_attr a_1 = {36, 7, 0, 0, "Z\001\000\000\000,\001\000\000\000Z\003\000\000\000,\001\000\000\000Z\002\000\000\0009\001\000\000\000"};
static const cob_field_attr a_2 = {36, 4, 0, 0, "Z\001\000\000\000,\001\000\000\000Z\002\000\000\0009\001\000\000\000"};
static const cob_field_attr a_3 = {36, 9, 0, 0, "$\001\000\000\000,\001\000\000\000$\003\000\000\000,\001\000\000\000$\003\000\000\000,\001\000\000\000$\002\000\000\0009\001\000\000\000"};
static const cob_field_attr a_4 = {33, 0, 0, 0, NULL};
static const cob_field_attr a_5 = {1, 0, 0, 0, NULL};
static const cob_field_attr a_6 = {16, 7, 0, 0, NULL};
static const cob_field_attr a_7 = {16, 4, 0, 0, NULL};
static const cob_field_attr a_8 = {16, 11, 0, 0, NULL};
static const cob_field_attr a_9 = {16, 3, 0, 0, NULL};
static const cob_field_attr a_10 = {16, 12, 0, 0, NULL};

/* Fields */

/* PROGRAM-ID : REIDAI08 */
static cob_field f_6	= {50, b_6, &a_4};	/* TOUR-MASTER-FILE_record */
static cob_field f_7	= {132, b_8, &a_4};	/* TOUR-CONTRACT-RECORDS */
static cob_field f_8	= {132, b_8, &a_4};	/* TOUR-CONTRACT-LIST_record */
static cob_field f_12	= {3, b_12, &a_9};	/* COUNTER */
static cob_field f_13	= {12, b_13, &a_10};	/* TEMP-EXPENSES-TOTAL */
static cob_field f_14	= {37, b_14, &a_5};	/* INPUT-FORMAT */
static cob_field f_17	= {7, b_14 + 15, &a_6};	/* IN-TOUR-EXPENSES */
static cob_field f_18	= {4, b_14 + 22, &a_7};	/* IN-TOUR-MEMBERS */
static cob_field f_19	= {11, b_14 + 26, &a_8};	/* IN-TOTAL-EXPENSES */
static cob_field f_20	= {47, b_20, &a_5};	/* PRINT-HEADER */
static cob_field f_27	= {43, b_27, &a_5};	/* PRINT-ARTICLE */
static cob_field f_30	= {9, b_27 + 12, &a_1};	/* PRINT-TOUR-EXPENSES */
static cob_field f_32	= {5, b_27 + 23, &a_2};	/* PRINT-TOUR-MEMBERS */
static cob_field f_34	= {13, b_27 + 30, &a_3};	/* PRINT-TOTAL-EXPENSES */

/* End of fields */


/* Constants */
static cob_field c_1	= {15, (unsigned char *)"TOUR-MASTER.DAT", &a_4};
static cob_field c_2	= {12, (unsigned char *)"SYSPRINT.DAT", &a_4};
static cob_field c_3	= {1, (unsigned char *)" ", &a_4};
static cob_field c_4	= {19, (unsigned char *)"-- PROGRAM START --", &a_4};
static cob_field c_5	= {20, (unsigned char *)"-- PROGRAM EXIT   --", &a_4};
static cob_field c_6	= {7, (unsigned char *)" IN  : ", &a_4};
static cob_field c_7	= {6, (unsigned char *)" OUT :", &a_4};

