/* Generated by            cobc 1.1.0 */
/* Generated from          beginner_kadai08.cbl */
/* Generated at             7 18 2015 00:03:28 JST */
/* GNU Cobol build date    May 19 2015 09:51:19 */
/* GNU Cobol package date  Jan 20 2014 07:40:53 UTC */
/* Compile command         cobc -x -free -g -debug -Wall beginner_kadai08.cbl */

#define  __USE_STRING_INLINES 1
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <libcob.h>

#define COB_SOURCE_FILE		"beginner_kadai08.cbl"
#define COB_PACKAGE_VERSION	"1.1"
#define COB_PATCH_LEVEL		0

/* Global variables */
#include "beginner_kadai08.c.h"

/* Function prototypes */

int REIDAI08 ();
static int REIDAI08_ (const int);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (REIDAI08 ());
}

/* Functions */

int
REIDAI08 ()
{
  return REIDAI08_ (0);
}

static int
REIDAI08_ (const int entry)
{
  /* Local variables */
  #include "beginner_kadai08.c.l.h"

  static int initialized = 0;
  static cob_field *cob_user_parameters[COB_MAX_FIELD_PARAMS];
  static struct cob_module module = { NULL, NULL, NULL, NULL, cob_user_parameters, 0, '.', '$', ',', 1, 1, 1, 0 };

  /* Start of function code */

  /* CANCEL callback handling */
  if (unlikely(entry < 0)) {
  	if (!initialized) {
  		return 0;
  	}
  	cob_close (h_TOUR_MASTER_FILE, 0, NULL);
  	cob_close (h_TOUR_CONTRACT_LIST, 0, NULL);
  	initialized = 0;
  	return 0;
  }

  /* Initialize frame stack */
  frame_ptr = &frame_stack[0];
  frame_ptr->perform_through = 0;
  frame_overflow = &frame_stack[COB_STACK_SIZE - 1];

  /* Push module stack */
  module.next = cob_current_module;
  cob_current_module = &module;

  /* Initialize program */
  if (unlikely(initialized == 0))
    {
      if (!cob_initialized) {
        cob_fatal_error (COB_FERROR_INITIALIZED);
      }
      cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
      (*(int *) (b_1)) = 0;
      *(unsigned char *)(b_9) = 48;
      *(b_10) = 49;
      *(b_11) = 48;
      memset (b_12, 48, 3);
      memset (b_13, 48, 12);
      memset (b_14, 32, 15);
      memset (b_14 + 15, 48, 22);
      memcpy (b_20, "\357\276\202\357\275", 5);
      memset (b_20 + 5, 32, 13);
      memcpy (b_20 + 18, "\357\276\230\357\275", 5);
      memcpy (b_20 + 23, "\357\276\206\357\276", 5);
      memset (b_20 + 28, 32, 14);
      memcpy (b_20 + 42, "ï½·ï¾", 5);
      memset (b_27, 32, 10);
      memset (b_27 + 10, 32, 2);
      cob_move (&cob_zero, &f_30);
      memset (b_27 + 21, 32, 2);
      cob_move (&cob_zero, &f_32);
      memset (b_27 + 28, 32, 2);
      cob_move (&cob_zero, &f_34);

      if (!h_TOUR_MASTER_FILE)
      {
        h_TOUR_MASTER_FILE = cob_malloc (sizeof(cob_file));
      }
      h_TOUR_MASTER_FILE->select_name = (const char *)"TOUR-MASTER-FILE";
      h_TOUR_MASTER_FILE->file_status = h_TOUR_MASTER_FILE_status;
      memset (h_TOUR_MASTER_FILE_status, '0', 2);
      h_TOUR_MASTER_FILE->assign = &c_1;
      h_TOUR_MASTER_FILE->record = &f_6;
      h_TOUR_MASTER_FILE->record_size = NULL;
      h_TOUR_MASTER_FILE->record_min = 0;
      h_TOUR_MASTER_FILE->record_max = 50;
      h_TOUR_MASTER_FILE->nkeys = 0;
      h_TOUR_MASTER_FILE->keys = NULL;
      h_TOUR_MASTER_FILE->file = NULL;
      h_TOUR_MASTER_FILE->organization = 1;
      h_TOUR_MASTER_FILE->access_mode = 1;
      h_TOUR_MASTER_FILE->lock_mode = 0;
      h_TOUR_MASTER_FILE->open_mode = 0;
      h_TOUR_MASTER_FILE->flag_optional = 0;
      h_TOUR_MASTER_FILE->last_open_mode = 0;
      h_TOUR_MASTER_FILE->special = 0;
      h_TOUR_MASTER_FILE->flag_nonexistent = 0;
      h_TOUR_MASTER_FILE->flag_end_of_file = 0;
      h_TOUR_MASTER_FILE->flag_begin_of_file = 0;
      h_TOUR_MASTER_FILE->flag_first_read = 0;
      h_TOUR_MASTER_FILE->flag_read_done = 0;
      h_TOUR_MASTER_FILE->flag_select_features = 0;
      h_TOUR_MASTER_FILE->flag_needs_nl = 0;
      h_TOUR_MASTER_FILE->flag_needs_top = 0;
      h_TOUR_MASTER_FILE->file_version = 0;
      if (!h_TOUR_CONTRACT_LIST)
      {
        h_TOUR_CONTRACT_LIST = cob_malloc (sizeof(cob_file));
      }
      h_TOUR_CONTRACT_LIST->select_name = (const char *)"TOUR-CONTRACT-LIST";
      h_TOUR_CONTRACT_LIST->file_status = h_TOUR_CONTRACT_LIST_status;
      memset (h_TOUR_CONTRACT_LIST_status, '0', 2);
      h_TOUR_CONTRACT_LIST->assign = &c_2;
      h_TOUR_CONTRACT_LIST->record = &f_8;
      h_TOUR_CONTRACT_LIST->record_size = NULL;
      h_TOUR_CONTRACT_LIST->record_min = 0;
      h_TOUR_CONTRACT_LIST->record_max = 132;
      h_TOUR_CONTRACT_LIST->nkeys = 0;
      h_TOUR_CONTRACT_LIST->keys = NULL;
      h_TOUR_CONTRACT_LIST->file = NULL;
      h_TOUR_CONTRACT_LIST->organization = 1;
      h_TOUR_CONTRACT_LIST->access_mode = 1;
      h_TOUR_CONTRACT_LIST->lock_mode = 0;
      h_TOUR_CONTRACT_LIST->open_mode = 0;
      h_TOUR_CONTRACT_LIST->flag_optional = 0;
      h_TOUR_CONTRACT_LIST->last_open_mode = 0;
      h_TOUR_CONTRACT_LIST->special = 0;
      h_TOUR_CONTRACT_LIST->flag_nonexistent = 0;
      h_TOUR_CONTRACT_LIST->flag_end_of_file = 0;
      h_TOUR_CONTRACT_LIST->flag_begin_of_file = 0;
      h_TOUR_CONTRACT_LIST->flag_first_read = 0;
      h_TOUR_CONTRACT_LIST->flag_read_done = 0;
      h_TOUR_CONTRACT_LIST->flag_select_features = 0;
      h_TOUR_CONTRACT_LIST->flag_needs_nl = 0;
      h_TOUR_CONTRACT_LIST->flag_needs_top = 0;
      h_TOUR_CONTRACT_LIST->file_version = 0;

      initialized = 1;
    }

  cob_save_call_params = cob_call_params;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Entry REIDAI08 */

  l_2:;

  /* MAIN SECTION */

  /* BASE */

  /* beginner_kadai08.cbl:95: DISPLAY */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 95, "MAIN SECTION", "BASE", "DISPLAY");
  {
    cob_display (0, 1, 1, &c_3);
  }
  /* beginner_kadai08.cbl:96: DISPLAY */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 96, "MAIN SECTION", "BASE", "DISPLAY");
  {
    cob_display (0, 1, 1, &c_4);
  }
  /* beginner_kadai08.cbl:99: PERFORM */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 99, "MAIN SECTION", "BASE", "PERFORM");
  {
    /* PERFORM INIT */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 5;
    frame_ptr->return_address = &&l_8;
    goto l_5;
    l_8:
    frame_ptr--;
  }
  /* beginner_kadai08.cbl:102: PERFORM */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 102, "MAIN SECTION", "BASE", "PERFORM");
  {
    for (;;)
      {
        if (((int)memcmp (b_9, b_10, 1) == 0))
          break;
        /* PERFORM MAIN-LOOP */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 6;
        frame_ptr->return_address = &&l_9;
        goto l_6;
        l_9:
        frame_ptr--;
      }
  }
  /* beginner_kadai08.cbl:106: PERFORM */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 106, "MAIN SECTION", "BASE", "PERFORM");
  {
    /* PERFORM FINALIZE */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address = &&l_10;
    goto l_7;
    l_10:
    frame_ptr--;
  }
  /* beginner_kadai08.cbl:109: DISPLAY */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 109, "MAIN SECTION", "BASE", "DISPLAY");
  {
    cob_display (0, 1, 1, &c_5);
  }
  /* beginner_kadai08.cbl:110: STOP */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 110, "MAIN SECTION", "BASE", "STOP");
  {
    cob_stop_run ((*(int *) (b_1)));
  }

  /* INIT */

  l_5:;
  /* beginner_kadai08.cbl:121: OPEN */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 121, "MAIN SECTION", "INIT", "OPEN");
  {
    cob_exception_code = 0;
    {
      cob_open (h_TOUR_MASTER_FILE, 1, 0, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_11;
        goto l_1;
        l_11:
        frame_ptr--;
      }
    cob_exception_code = 0;
    {
      cob_open (h_TOUR_CONTRACT_LIST, 2, 1, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_12;
        goto l_1;
        l_12:
        frame_ptr--;
      }
  }
  /* beginner_kadai08.cbl:127: WRITE */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 127, "MAIN SECTION", "INIT", "WRITE");
  cob_exception_code = 0;
  {
    cob_move (&f_20, &f_7);
    cob_write (h_TOUR_CONTRACT_LIST, &f_7, 1179648, NULL);
  }
  if (unlikely(cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
          cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address = &&l_13;
      goto l_1;
      l_13:
      frame_ptr--;
    }
  /* beginner_kadai08.cbl:130: READ */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 130, "MAIN SECTION", "INIT", "READ");
  cob_exception_code = 0;
  {
    cob_read (h_TOUR_MASTER_FILE, 0, NULL, 1);
  }
  if (unlikely(cob_exception_code != 0))
    {
      if (cob_exception_code == 0x0501)
        {
          {
            /* beginner_kadai08.cbl:131: MOVE */
            cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 131, "MAIN SECTION", "INIT", "MOVE");
            {
              *(b_9) = *(b_10);
            }
          }
        }
      else
        {
          /* PERFORM Default Error Handler */
          frame_ptr++;
          if (unlikely(frame_ptr == frame_overflow))
              cob_fatal_error (COB_FERROR_STACK);
          frame_ptr->perform_through = 1;
          frame_ptr->return_address = &&l_14;
          goto l_1;
          l_14:
          frame_ptr--;
        }
    }
  else
    {
      memcpy (b_14, b_6, 37);
    }

  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address;

  /* MAIN-LOOP */

  l_6:;
  /* beginner_kadai08.cbl:140: DISPLAY */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 140, "MAIN SECTION", "MAIN-LOOP", "DISPLAY");
  {
    cob_display (0, 1, 2, &c_6, &f_14);
  }
  /* beginner_kadai08.cbl:148: MOVE */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 148, "MAIN SECTION", "MAIN-LOOP", "MOVE");
  {
    memcpy (b_27, b_14 + 5, 10);
  }
  /* beginner_kadai08.cbl:149: MOVE */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 149, "MAIN SECTION", "MAIN-LOOP", "MOVE");
  {
    cob_move (&f_17, &f_30);
  }
  /* beginner_kadai08.cbl:150: MOVE */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 150, "MAIN SECTION", "MAIN-LOOP", "MOVE");
  {
    cob_move (&f_18, &f_32);
  }
  /* beginner_kadai08.cbl:151: MOVE */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 151, "MAIN SECTION", "MAIN-LOOP", "MOVE");
  {
    cob_move (&f_19, &f_34);
  }
  /* beginner_kadai08.cbl:154: DISPLAY */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 154, "MAIN SECTION", "MAIN-LOOP", "DISPLAY");
  {
    cob_display (0, 1, 2, &c_7, &f_27);
  }
  /* beginner_kadai08.cbl:155: DISPLAY */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 155, "MAIN SECTION", "MAIN-LOOP", "DISPLAY");
  {
    cob_display (0, 1, 1, &c_3);
  }
  /* beginner_kadai08.cbl:156: WRITE */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 156, "MAIN SECTION", "MAIN-LOOP", "WRITE");
  cob_exception_code = 0;
  {
    cob_move (&f_27, &f_7);
    cob_write (h_TOUR_CONTRACT_LIST, &f_7, (1114112 + 1), NULL);
  }
  if (unlikely(cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
          cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address = &&l_15;
      goto l_1;
      l_15:
      frame_ptr--;
    }
  /* beginner_kadai08.cbl:159: READ */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 159, "MAIN SECTION", "MAIN-LOOP", "READ");
  cob_exception_code = 0;
  {
    cob_read (h_TOUR_MASTER_FILE, 0, NULL, 1);
  }
  if (unlikely(cob_exception_code != 0))
    {
      if (cob_exception_code == 0x0501)
        {
          {
            /* beginner_kadai08.cbl:160: MOVE */
            cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 160, "MAIN SECTION", "MAIN-LOOP", "MOVE");
            {
              *(b_10) = *(b_9);
            }
          }
        }
      else
        {
          /* PERFORM Default Error Handler */
          frame_ptr++;
          if (unlikely(frame_ptr == frame_overflow))
              cob_fatal_error (COB_FERROR_STACK);
          frame_ptr->perform_through = 1;
          frame_ptr->return_address = &&l_16;
          goto l_1;
          l_16:
          frame_ptr--;
        }
    }
  else
    {
      memcpy (b_14, b_6, 37);
    }

  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address;

  /* FINALIZE */

  l_7:;
  /* beginner_kadai08.cbl:168: MOVE */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 168, "MAIN SECTION", "FINALIZE", "MOVE");
  {
    memset (b_27, 32, 43);
  }
  /* beginner_kadai08.cbl:169: MOVE */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 169, "MAIN SECTION", "FINALIZE", "MOVE");
  {
    memcpy (b_27, "\357\275\272\357\276\236\357\275\263\357", 10);
  }
  /* beginner_kadai08.cbl:170: MOVE */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 170, "MAIN SECTION", "FINALIZE", "MOVE");
  {
    cob_move (&f_12, &f_32);
  }
  /* beginner_kadai08.cbl:171: MOVE */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 171, "MAIN SECTION", "FINALIZE", "MOVE");
  {
    cob_move (&f_13, &f_34);
  }
  /* beginner_kadai08.cbl:174: DISPLAY */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 174, "MAIN SECTION", "FINALIZE", "DISPLAY");
  {
    cob_display (0, 1, 1, &f_27);
  }
  /* beginner_kadai08.cbl:175: WRITE */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 175, "MAIN SECTION", "FINALIZE", "WRITE");
  cob_exception_code = 0;
  {
    cob_move (&f_27, &f_7);
    cob_write (h_TOUR_CONTRACT_LIST, &f_7, (1114112 + 2), NULL);
  }
  if (unlikely(cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
          cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address = &&l_17;
      goto l_1;
      l_17:
      frame_ptr--;
    }
  /* beginner_kadai08.cbl:178: CLOSE */
  cob_set_location ("REIDAI08", "beginner_kadai08.cbl", 178, "MAIN SECTION", "FINALIZE", "CLOSE");
  {
    cob_exception_code = 0;
    {
      cob_close (h_TOUR_MASTER_FILE, 0, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_18;
        goto l_1;
        l_18:
        frame_ptr--;
      }
    cob_exception_code = 0;
    {
      cob_close (h_TOUR_CONTRACT_LIST, 0, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_19;
        goto l_1;
        l_19:
        frame_ptr--;
      }
  }

  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address;

  /* Program exit */

  /* Pop module stack */
  cob_current_module = cob_current_module->next;

  /* Program return */
  return (*(int *) (b_1));


  /* Default Error Handler */

  l_1:;

  if (!(cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS)) {
  	cob_default_error_handle ();
  	cob_stop_run (1);
  }

  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address;

  cob_fatal_error (COB_FERROR_CODEGEN);

}

/* End functions */

