/* Generated by            cobc 1.1.0 */
/* Generated from          hello.cbl */
/* Generated at             7 18 2015 00:01:34 JST */
/* GNU Cobol build date    May 19 2015 09:51:19 */
/* GNU Cobol package date  Jan 20 2014 07:40:53 UTC */
/* Compile command         cobc -x -free -g -debug -Wall hello.cbl */

/* Frame stack declaration */
struct cob_frame {
	int	perform_through;
	void	*return_address;
};

/* Union for CALL statement */
union cob_call_union {
	void *(*funcptr)();
	int  (*funcint)();
	void *func_void;
};
union cob_call_union	cob_unifunc;


/* Data storage */

/* PROGRAM-ID : HELLO */
static unsigned char b_1[4] __attribute__((aligned));	/* RETURN-CODE */
static unsigned char b_5[20] __attribute__((aligned));	/* MY-DATA1 */

/* End of data storage */


/* Attributes */

static const cob_field_attr a_1 = {33, 0, 0, 0, NULL};

/* Fields */

/* PROGRAM-ID : HELLO */
static cob_field f_5	= {20, b_5, &a_1};	/* MY-DATA1 */

/* End of fields */

