/* Generated by            cobc 1.1.0 */
/* Generated from          hello.cbl */
/* Generated at             7 18 2015 00:01:34 JST */
/* GNU Cobol build date    May 19 2015 09:51:19 */
/* GNU Cobol package date  Jan 20 2014 07:40:53 UTC */
/* Compile command         cobc -x -free -g -debug -Wall hello.cbl */


/* Define perform frame stack */

struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];

