/* Generated by            cobc 1.1.0 */
/* Generated from          hello.cbl */
/* Generated at             7 18 2015 00:01:34 JST */
/* GNU Cobol build date    May 19 2015 09:51:19 */
/* GNU Cobol package date  Jan 20 2014 07:40:53 UTC */
/* Compile command         cobc -x -free -g -debug -Wall hello.cbl */

#define  __USE_STRING_INLINES 1
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <libcob.h>

#define COB_SOURCE_FILE		"hello.cbl"
#define COB_PACKAGE_VERSION	"1.1"
#define COB_PATCH_LEVEL		0

/* Global variables */
#include "hello.c.h"

/* Function prototypes */

int HELLO ();
static int HELLO_ (const int);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (HELLO ());
}

/* Functions */

int
HELLO ()
{
  return HELLO_ (0);
}

static int
HELLO_ (const int entry)
{
  /* Local variables */
  #include "hello.c.l.h"

  static int initialized = 0;
  static cob_field *cob_user_parameters[COB_MAX_FIELD_PARAMS];
  static struct cob_module module = { NULL, NULL, NULL, NULL, cob_user_parameters, 0, '.', '$', ',', 1, 1, 1, 0 };

  /* Start of function code */

  /* CANCEL callback handling */
  if (unlikely(entry < 0)) {
  	if (!initialized) {
  		return 0;
  	}
  	initialized = 0;
  	return 0;
  }

  /* Initialize frame stack */
  frame_ptr = &frame_stack[0];
  frame_ptr->perform_through = 0;
  frame_overflow = &frame_stack[COB_STACK_SIZE - 1];

  /* Push module stack */
  module.next = cob_current_module;
  cob_current_module = &module;

  /* Initialize program */
  if (unlikely(initialized == 0))
    {
      if (!cob_initialized) {
        cob_fatal_error (COB_FERROR_INITIALIZED);
      }
      cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
      (*(int *) (b_1)) = 0;
      memset (b_5, 32, 20);
      initialized = 1;
    }

  cob_save_call_params = cob_call_params;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Entry HELLO */

  l_2:;

  /* MAIN SECTION */

  /* MAIN PARAGRAPH */

  /* hello.cbl:16: MOVE */
  cob_set_location ("HELLO", "hello.cbl", 16, "MAIN", "MAIN PARAGRAPH", "MOVE");
  {
    memcpy (b_5, "HELLO WORLD!!       ", 20);
  }
  /* hello.cbl:17: DISPLAY */
  cob_set_location ("HELLO", "hello.cbl", 17, "MAIN", "MAIN PARAGRAPH", "DISPLAY");
  {
    cob_display (0, 1, 1, &f_5);
  }
  /* hello.cbl:18: DISPLAY */
  cob_set_location ("HELLO", "hello.cbl", 18, "MAIN", "MAIN PARAGRAPH", "DISPLAY");
  {
    cob_display (0, 1, 1, &f_5);
  }
  /* hello.cbl:20: STOP */
  cob_set_location ("HELLO", "hello.cbl", 20, "MAIN", "MAIN PARAGRAPH", "STOP");
  {
    cob_stop_run ((*(int *) (b_1)));
  }

  /* Program exit */

  /* Pop module stack */
  cob_current_module = cob_current_module->next;

  /* Program return */
  return (*(int *) (b_1));
}

/* End functions */

